### ISSUE TITLE
ngRepeat:dupes: Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repea...

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/maas-ui#1386]
https://sentry.is.canonical.com/canonical/maas-ui/issues/10604/?referrer=github_plugin

```
ngRepeat:dupes: Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: ip in $vs_collection track by ip.ip, Duplicate key: 10.10.15.191, Duplicate value: 
  at minErr/< (/MAAS/r/1.4d60becd58cd8d3cc327.js:3957:407)
  at ngRepeatAction (/MAAS/r/1.4d60becd58cd8d3cc327.js:22098:100)
  at $watchCollectionAction (/MAAS/r/1.4d60becd58cd8d3cc327.js:12375:237)
  at $digest (/MAAS/r/1.4d60becd58cd8d3cc327.js:12439:227)
  at $apply (/MAAS/r/1.4d60becd58cd8d3cc327.js:12663:163)
...
(7 additional frame(s) were not displayed)

ngRepeat:dupes: Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: ip in $vs_collection track by ip.ip, Duplicate key: 10.10.15.191, Duplicate value: 
```

**Comment by squidsoup** [comment]
@anthonydillon will investigate if this exists in 2.9, but probably won't fix if only in released version as it is a warning, rather than a error.

**Comment by squidsoup** [comment]
Have filed https://bugs.launchpad.net/maas/+bug/1889142, will reopen if any UI changes are required, although this appears to be a server issue.
