### ISSUE TITLE
Error: Unknown data: undefined

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#1399]
https://sentry.is.canonical.com/canonical/maas-ui/issues/9523/?referrer=github_plugin

```
Error: Unknown data: undefined
  at GeneralManager._getInternalData (/MAAS/r/1.655e38a7cfa27fc32943.js:33792:147)
  at GeneralManager.isDataLoaded (/MAAS/r/1.655e38a7cfa27fc32943.js:33795:66)
  at updateAvailableActionOptions (/MAAS/r/1.655e38a7cfa27fc32943.js:34538:276)
  at Scope.$digest (/MAAS/r/1.655e38a7cfa27fc32943.js:12439:227)
  at Scope.$apply (/MAAS/r/1.655e38a7cfa27fc32943.js:12663:163)
...
(3 additional frame(s) were not displayed)
```

**Comment by huwshimi** [comment]
To reproduce:
- Visit a machine e.g. /MAAS/l/machine/76pa3f
- Stop the server
- Wait a few seconds and start it again
- When the ws reconnects again you should see the error
