### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1438]
https://sentry.is.canonical.com/canonical/maas-ui/issues/10229/?referrer=github_plugin

```
TypeError: Cannot read property 'forEach' of undefined
  at Scope.NodesListController.$scope.actionCancel (/MAAS/r/1.655e38a7cfa27fc32943.js:34864:199)
  at fn (/MAAS/r/1.655e38a7cfa27fc32943.js:11536:8)
  at callback (/MAAS/r/1.655e38a7cfa27fc32943.js:18726:143)
  at Scope.$eval (/MAAS/r/1.655e38a7cfa27fc32943.js:12589:57)
  at Scope.$apply (/MAAS/r/1.655e38a7cfa27fc32943.js:12663:73)
...
(3 additional frame(s) were not displayed)
```

**Comment by huwshimi** [comment]
To reproduce:
- Visit /MAAS/l/controllers
- Check a controller
- Open the delete form using the take action menu
- Click cancel and you should see the error

**Comment by huwshimi** [comment]
This was fixed by: https://github.com/canonical-web-and-design/maas-ui/pull/2505
