### ISSUE TITLE
ngRepeat:dupes: Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repea...

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1439]
https://sentry.is.canonical.com/canonical/maas-ui/issues/11130/?referrer=github_plugin

```
ngRepeat:dupes: Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: confirmation_detail in action.confirmation_details, Duplicate key: string:netiposserver.maas is the primary rack controller for 
  at None (/MAAS/r/1.655e38a7cfa27fc32943.js:3956:427)
  at ngRepeatAction (/MAAS/r/1.655e38a7cfa27fc32943.js:22097:114)
  at $watchCollectionAction (/MAAS/r/1.655e38a7cfa27fc32943.js:12374:245)
  at $digest (/MAAS/r/1.655e38a7cfa27fc32943.js:12438:229)
  at $apply (/MAAS/r/1.655e38a7cfa27fc32943.js:12662:2262)
...
(2 additional frame(s) were not displayed)

ngRepeat:dupes: Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: confirmation_detail in action.confirmation_details, Duplicate key: string:netiposserver.maas is the primary rack controller for 
```

**Comment by huwshimi** [comment]
To reproduce:
- Visit /MAAS/l/controllers
- Check a controller
- Open the delete form using the take action menu
- Click delete and you should see the error
