### ISSUE TITLE
Error: application 'legacy' died in status BOOTSTRAPPING: {"isTrusted":true}

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1459]
https://sentry.is.canonical.com/canonical/maas-ui/issues/10348/?referrer=github_plugin

```
Error: application 'legacy' died in status BOOTSTRAPPING: {"isTrusted":true}
  at f (/MAAS/r/root-application.e9e167161aa8d2a80ba5.js:439:11)
  at u (/MAAS/r/root-application.e9e167161aa8d2a80ba5.js:397:11)
  at None (/MAAS/r/root-application.e9e167161aa8d2a80ba5.js:530:14)
```

**Comment by huwshimi** [comment]
I just hit this and am able to reproduce in Firefox in a new private window (not logged in to MAAS) and visiting a legacy url e.g. /MAAS/l/controllers a few times and it sometimes hits the error.
