### ISSUE TITLE
ChunkLoadError: application 'ui' died in status LOADING_SOURCE_CODE: Loading chunk 2 failed.

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1618]
https://sentry.is.canonical.com/canonical/maas-ui/issues/9962/?referrer=github_plugin

```
ChunkLoadError: application 'ui' died in status LOADING_SOURCE_CODE: Loading chunk 2 failed.
(error: http://maas.local:5240/MAAS/r/2.d45263d00b22649aa0bc.js)
  at (error:  (/MAAS/r/2.d45263d00b22649aa0bc.js))
  at Function.requireEnsure [as e] (/MAAS/r/root-application.079702b5b63ff680ca5a.js:106:26)
  at Object.app [as loadApp] (/MAAS/r/root-application.079702b5b63ff680ca5a.js:1580:32)
  at None (/MAAS/r/root-application.079702b5b63ff680ca5a.js:798:17)
```

**Comment by huwshimi** [comment]
To reproduce (network issues will also cause this to happen I think):
- Load maas-ui at a legacy url e.g. /MAAS/l/images (without having first visited a React url).
- Stop your server.
- Click on a React URL in the header.
- You should see the error in your console.
