### ISSUE TITLE
Error: [$rootScope:inprog] null already in progress

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#1811]
https://sentry.is.canonical.com/canonical/maas-ui/issues/7925/?referrer=github_plugin

```
Error: [$rootScope:inprog] null already in progress
https://errors.angularjs.org/1.7.9/$rootScope/inprog?p0=null
  at None (/MAAS/r/1.6f85774a2928f988cdb6.js:3956:427)
  at beginPhase (/MAAS/r/1.6f85774a2928f988cdb6.js:12761:267)
  at $digest (/MAAS/r/1.6f85774a2928f988cdb6.js:12427:2476)
  at None (/MAAS/r/1.6f85774a2928f988cdb6.js:12619:111)
  at completeTask (/MAAS/r/1.6f85774a2928f988cdb6.js:13741:1380)
...
(2 additional frame(s) were not displayed)
```

**Comment by huwshimi** [comment]
I haven't managed to reproduce this one. According to [this issue](https://stackoverflow.com/questions/40982853/weird-angular-exception-rootscopeinprog-null-already-in-progress) it's something that only shows up in Safari, and that's what Sentry is showing us as well. However, I haven't figured out how to make it happen.

**Comment by huwshimi** [comment]
This is also is in machine details which is being rebuilt this cycle.
