### ISSUE TITLE
Typing in machine list search has an error

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/maas-ui#3531]
Go to the machine list and type something in the search box.
See that when you stop typing the search box loses focus and there is an error in the console:
```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at DebounceSearchBox (http://dev.local:8400/static/js/main.chunk.js:6031:3)
    at div
    at Col (http://dev.local:8400/static/js/vendors~main.chunk.js:3348:23)
    at div
    at Row (http://dev.local:8400/static/js/vendors~main.chunk.js:7893:23)
    at MachineListControls (http://dev.local:8400/static/js/main.chunk.js:139146:3)
    at MachineList (http://dev.local:8400/static/js/main.chunk.js:138733:3)
    at component
```

**Comment by huwshimi** [comment]
The search box also loses focus in the cluster vm list.

**Comment by huwshimi** [comment]
These issues were a symptom of the same issue that caused: https://github.com/canonical-web-and-design/maas-ui/issues/3533.
