### ISSUE TITLE
TypeError: e is undefined

### ISSUE THREAD

**Issue by squidsoup** [canonical-web-and-design/maas-ui#893]
https://sentry.is.canonical.com/canonical/maas-ui/issues/7050/?referrer=github_plugin

```
TypeError: e is undefined
  at Bt/e.isBond (/MAAS/assets/js/maas.065622b8389de44c2b50.bundle.js:113:92624)
  at fn (/MAAS/assets/js/maas.065622b8389de44c2b50.bundle.js%20line%2041%20%3E%20Function:4:261)
  at $digest (/MAAS/assets/js/maas.065622b8389de44c2b50.bundle.js:41:100398)
  at $apply (/MAAS/assets/js/maas.065622b8389de44c2b50.bundle.js:41:102381)
  at compile/</< (/MAAS/assets/js/maas.065622b8389de44c2b50.bundle.js:41:150922)
...
(3 additional frame(s) were not displayed)
```

**Comment by sparkiegeek** [comment]
Steps to reproduce:

1. http://bolla.internal:5240/MAAS/#/machine/fd7wtc?area=network
1b) Manually click network because the URL routing switcharoo isn't working
2. Add an interface
3. Mark it as connected from the in-table action
4. Select the new interface
5. Click Add bridge
6. Click Cancel

Look in Console and see traceback
